Feature/sign cancelacion
lunasoft/sw-tools-dotnet pull request #26
Opened 2022-03-14 20:38 UTC by SwAeyrton

- Se agrega metodo para sellar XML de cancelacion.
- Se agrega metodo para crear XML de cancelacion.
- Se agrega BuildSettings.cs para UT
- Se actualiza version a 1.0.3.1

2022-03-15 00:16 UTC, martinfnsw reviewed
El token puede ser utilizado por más usuarios

2022-03-15 00:28 UTC, JuanGamezSW requested changes

2022-03-15 00:28 UTC, JuanGamezSW commented on SW.Tools/Helpers/Xml.cs
> +        /// <param name="foliosFiscales">Lista de folios a cancelar con el formato uuid,motivo,uuidSustitucion</param>
No es intuitivo el uso y tampoco lo veo tan bien hacerlo de esta manera, que pasa cuando el motivo lleva una ","?

Sugiero cambiarlo por un Dictionary<string, CancelationReason>, donde el string corresponde con el UUID y CancelationReason sea una clase que tenga las propiedades de reason y uuidSubstitution, donde ya puedes ponerle propiedades que te indiquen si el motivo requiere de algun folio de sustitucion o que te de el string.empty.

Incluso de esta manera puedes tener un enum de los posibles reason con una breve descripcion.

2022-03-15 00:28 UTC, JuanGamezSW commented on SW.Tools/Services/Sign/Sign.cs
> +                    if (folios.Count > 10000)
No recomiendo usar mas alla de 500, porque entre mas UUID lleve mas va tardar la peticion llegando a que de timeout y te quedes sin el acuse de cancelacion.

2022-04-06 14:18 UTC, martinfnsw approved these changes

2022-04-06 16:07 UTC, JuanGamezSW approved these changes

2022-04-07 16:43 UTC, merged