Update SignServices
lunasoft/sw-tools-dotnet pull request #41
Opened 2022-10-07 16:29 UTC by martinfnsw

- Update SignResponse
- Update SignService
- Add  exceptions

2022-10-07 19:12 UTC, SwAeyrton requested changes

2022-10-07 19:12 UTC, SwAeyrton commented on SW.ToolsUT/UT_Tools_Sign.cs
>          {
Las UT de error por alguna razon no dan error, deberia ser un assert true de que CadenaOriginal sea diferente a lo que se obtiene en el result_

2022-10-07 19:12 UTC, SwAeyrton commented on SW.ToolsUT/UT_Tools_Sign.cs
>              Assert.IsTrue(selloOriginal.Equals(sello));
en varias UT faltan los assert de status, validando si es error o success

2022-10-10 21:14 UTC, martinfnsw commented on SW.ToolsUT/UT_Tools_Sign.cs
>              Assert.IsTrue(selloOriginal.Equals(sello));
Modifique algunas, pero falta reestructurar las de cadena original

2022-10-10 21:34 UTC, SwAeyrton approved these changes

2022-10-10 22:39 UTC, ReyesSW approved these changes
Veo bien los cambios.

2022-10-10 22:51 UTC, merged