Release/1.0.11.1
lunasoft/sw-tools-dotnet pull request #57
Opened 2024-01-19 20:09 UTC by FerCarrilloM

2024-01-19 20:17 UTC, SebastianSW approved these changes

2024-01-23 16:55 UTC, SwAeyrton approved these changes

2024-01-23 17:09 UTC, SwAeyrton commented
voy a lanzar un bugfix porque en develop hay un error de compilacion

2024-01-23 17:22 UTC, ReyesSW approved these changes

2024-01-24 01:17 UTC, SwAeyrton commented
Hay algo raro en tu release, hay cosas que no estan en develop pero en tu release si, por ejemplo 
![image](https://github.com/lunasoft/sw-tools-dotnet/assets/88451104/ff1f69c7-84f7-4977-b56a-50b802012ed2)
Lo cual causa un error de compilacion, ese doble metodo no esta en develop ni en master, como si se hubieran unido en tu release por alguna razon, yo sugiero crear nuevamente la rama cuidando que se haga desde la ultima version de develop

2024-01-24 01:18 UTC, SwAeyrton requested changes
.

2024-01-24 15:01 UTC, closed without merging